[package]
name = "prng-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3"
nanorand = "0.7"
rand = { version = "0.9", features = ["small_rng"] }
rand_xoshiro = "0.7"

[profile.release]
opt-level = 3
lto = "fat"

[profile.dev]
opt-level = 1
lto = "thin"
